name: Deploy with Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Index.html to Nginx
        run: |
          sudo cp Index.html /usr/share/nginx/html/Index.html
    