name: my-deployment

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  deploy:
    needs: build
    runs-on: self-hosted+
    steps:
      - name: Bala
        run: |
          scp -r ./index.html /usr/share/nginx/html/
    